### ISSUE TITLE
thoughts on `civic.json`

### ISSUE THREAD

**Issue by ajschumacher** [codefordc/codefordc.github.com#134]
- Should `civic.json` have it's own repo? Maybe in collaboration with the Beta folks? I don't know if they're actively developing/using it; @stvnrlly?
- Would it be better to change the spec to not encode information in keys? This would mean changing `politicalEntity`, `governmentPartner`, `communityPartner`, and `data` to be more like `needs`; perhaps like "an array of `politicalEntity` objects, each of which has keys `name` and `url`."
- Right now the item numbered 12 is really a sub-point of its predecessor; can the structure of the document show this? (Also, I think the text in 12 doesn't make it clear that it expects these needs and wants to be objects with a single key, either `need` or `want`.
- The needs and wants are likely to change frequently and might be better left to an issue management system such as github's no?
- Could the text explaining `categories` more clearly state that its expecting an array of objects with a certain structure?

**Comment by stvnrlly** [comment]
These are all good points. To a large extent, the answers are determined by how far we want to stray from the original BetaNYC spec, which was recently ["finished"](https://github.com/BetaNYC/civic.json/commit/60d92aca29c055e996c24bf1701f6e74a6bb417b). So far, the only things that I've done have been to add on top of it, but I think we might want to consider stuff like this. If we do, it would be best to do it all at once as civic.json 2.0 or something, so that people don't get tired of constantly having to add/change things.

**Comment by ajschumacher** [comment]
wait DC civic.json is a fork of NYC civic.json? hmm maybe DC shouldn't maintain a separate spec and instead develop together with them then?

**Comment by stvnrlly** [comment]
Yep, I believe that the goal is to have something that all Code for America brigades to use. I'll definitely be bringing our version back to BetaNYC to see if we can merge them.

**Comment by ajschumacher** [comment]
:+1:

**Comment by mkalish** [comment]
Closing this issue since this exists https://github.com/codefordc/civic.json
