### ISSUE TITLE
Better indication of form submission

### ISSUE THREAD

**Issue by stvnrlly** [codefordc/codefordc.github.com#169]
Since it takes a second or two to get confirmation, people using our contact form often submit multiple times. This could be helped by making the button give an indication of submission, and then return it to its original state once the confirmation alert pops up.

**Comment by sco-bo** [comment]
@stvnrlly, I like the spinner that's currently on the submit button, but I wonder if it would make things even more clear to 'fix' the alert message to the top of the page?

**Comment by stvnrlly** [comment]
Hey @sco-bo, thanks for the feedback. Could you say more about what you mean by "fix"?

**Comment by sco-bo** [comment]
@stvnrlly by that I mean to style the flash message almost like a fixed header, so that it's affixed to the top of the viewport. Because currently when you hit submit, the submit button spins around (which is helpful), but you actually have to scroll up to see the success message. Does what I'm saying make sense, just make it more apparent that the submission was successful

**Comment by stvnrlly** [comment]
Yep, that makes sense. Would it also work to scroll the user up to the top of the page?

**Comment by mkalish** [comment]
closed by #212
