### ISSUE TITLE
In addition to the Help Wanted tickets page, there should be one listing first time contributor tickets

### ISSUE THREAD

**Issue by mkalish** [codefordc/codefordc.github.com#178]
As more projects start to use the "First-time contributor" label, those issues should get pulled into the site

**Comment by LibanTheDev** [comment]
Hey is it alright if I tackle this issue??

**Comment by stvnrlly** [comment]
I certainly don't mind, though you should know that this will also require a change to the script in https://github.com/codefordc/files in order to find those labels.

The big question is probably whether this should be a separate page or another option on the `help wanted` page. I kind of like the latter idea, as it makes the information a little bit more accessible.

**Comment by LibanTheDev** [comment]
I was thinking it should just be an addition to the help wanted page. And that's fine I was expecting to change more than a few scripts. I'm totally up for it :-)

**Comment by LibanTheDev** [comment]
Hi, i'm getting an error when running the civic_json.py script. Specifically at this line: `exec(compile(open(path + "/creds.py").read(), path + "/creds.py", 'exec'))` where might I be able to find the creds.py script?

**Comment by stvnrlly** [comment]
You'll have to create the creds.py file yourself. The format is something like:

```
GITHUB_TOKEN = "my_token_here"
```

**Comment by mkalish** [comment]
This issue seems to have stalled and is probably better off on the project management repo.
